name: shared_ui
description: HavenKeep shared UI â€” theme, design system, reusable widgets.
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  shared_models:
    path: ../shared_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
